# Generated by Django 4.2.5 on 2023-11-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.CharField(
                choices=[
                    ("action", "ACTION"),
                    ("adventure", "ADVENTURE"),
                    ("animation", "ANIMATION"),
                    ("comedy", "COMEDY"),
                    ("documentary", "DOCUMENTARY"),
                    ("drama", "DRAMA"),
                    ("family", "FAMILY"),
                    ("fantasy", "FANTASY"),
                    ("history", "HISTORY"),
                    ("horror", "HORROR"),
                    ("music", "MUSIC"),
                    ("mystery", "MYSTERY"),
                    ("romance", "ROMANCE"),
                    ("sci-fi", "SCI-FI"),
                    ("tv-movie", "TV-MOVIE"),
                    ("thriller", "THRILLER"),
                    ("war", "WAR"),
                    ("western", "WESTERN"),
                ],
                max_length=20,
            ),
        ),
    ]
