# Generated by Django 4.2.5 on 2023-11-11 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_movie_genres"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="views_count",
            new_name="view_count",
        ),
    ]
