# Generated by Django 4.2.5 on 2023-11-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_rename_views_count_movie_view_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="description",
            new_name="overview",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="image",
            new_name="poster",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="year_of_production",
            new_name="release_date",
        ),
        migrations.AddField(
            model_name="movie",
            name="vote_average",
            field=models.IntegerField(default=3),
        ),
    ]
