# Generated by Django 4.2.5 on 2023-11-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_rename_description_movie_overview_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("action", "ACTION"),
                            ("adventure", "ADVENTURE"),
                            ("animation", "ANIMATION"),
                            ("comedy", "COMEDY"),
                            ("documentary", "DOCUMENTARY"),
                            ("drama", "DRAMA"),
                            ("family", "FAMILY"),
                            ("fantasy", "FANTASY"),
                            ("history", "HISTORY"),
                            ("horror", "HORROR"),
                            ("music", "MUSIC"),
                            ("mystery", "MYSTERY"),
                            ("romance", "ROMANCE"),
                            ("sci-fi", "SCI-FI"),
                            ("tv-movie", "TV-MOVIE"),
                            ("thriller", "THRILLER"),
                            ("war", "WAR"),
                            ("western", "WESTERN"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="movie",
            name="genres",
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(to="movies.genre"),
        ),
    ]
