# Generated by Django 4.2.5 on 2023-11-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_genre_remove_movie_genres_movie_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
