# Generated by Django 4.2.5 on 2023-11-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_alter_genre_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="tmdb_id",
            field=models.IntegerField(default=862),
        ),
    ]
