# Generated by Django 4.2.5 on 2023-11-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0008_movie_tagline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="cast",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="movie",
            name="directors",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="movie",
            name="overview",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(blank=True, upload_to="movies"),
        ),
    ]
