# Generated by Django 4.2.5 on 2023-11-17 23:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0009_alter_movie_cast_alter_movie_directors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="cast",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="directors",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="overview",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="poster",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="release_date",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="tagline",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="vote_average",
        ),
    ]
